---
title: "Raster"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
library("raster")
library("rgdal")
library("sf")
library("tidyverse")
```

```{r}
# load data
BLUE <- raster("Merced20211008/LC08_CU_002009_20211008_20211022_02_TOA_B2.tif")
GREEN <- raster("Merced20211008/LC08_CU_002009_20211008_20211022_02_TOA_B3.tif")
RED <- raster("Merced20211008/LC08_CU_002009_20211008_20211022_02_TOA_B4.tif")
NIR <- raster("Merced20211008/LC08_CU_002009_20211008_20211022_02_TOA_B5.tif")
SWIR <- raster("Merced20211008/LC08_CU_002009_20211008_20211022_02_TOA_B6.tif")

merced_road_shp <- st_read("Merced_County_Road_Centerlines/Road_Centerlines.shp")
```

https://eos.com/blog/6-spectral-indexes-on-top-of-ndvi-to-make-your-vegetation-analysis-complete/

# ARVI

```{r}
ARVI <- (NIR - 2*RED + BLUE) / (NIR + 2*RED + BLUE)
```

```{r}
ARVI_df <- ARVI %>%
  projectRaster(crs = "+proj=longlat +datum=WGS84") %>%
  as("SpatialPixelsDataFrame") %>% 
  as.data.frame()
```

```{r}
Merced_ARVI_df <- ARVI_df %>%
  filter(x > -120.55) %>%
  filter(x < -120.40) %>%
  filter(y > 37.27) %>%
  filter(y < 37.38)
```

```{r}
summary(Merced_ARVI_df$layer)
```

```{r}
plot_ARVI <- Merced_ARVI_df %>%
  ggplot() +
  geom_tile(aes(x = x, y = y, fill = layer)) +
  geom_sf(data = merced_road_shp) +
  xlim(-120.55, -120.40) +
  ylim(37.27, 37.38) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "black", hjust = 0.5, size = 15),
        plot.title = element_text(color = "darkgreen", hjust = 0.5, size = 30)) + 
  scale_fill_gradient(low = "gray", high = "green", name = "ARVI") +
  labs(title = "ARVI",
       subtitle = "30 Day Map Challenge Day 10: Raster",
       caption = "USGS LandSat8 Data",
       x = "", y = "")
```


# EVI

```{r, eval = FALSE}
C1 <- 6
C2 <- 7.5
L  <- 1
EVI <- 2.5*((NIR - RED) / (NIR + C1*RED - C2*BLUE + L))
```

```{r, eval = FALSE}
EVI_df <- EVI %>%
  projectRaster(crs = "+proj=longlat +datum=WGS84") %>%
  as("SpatialPixelsDataFrame") %>% 
  as.data.frame()
```

```{r, eval = FALSE}
Merced_EVI_df <- EVI_df %>%
  filter(x > -120.55) %>%
  filter(x < -120.40) %>%
  filter(y > 37.27) %>%
  filter(y < 37.38)
```

```{r, eval = FALSE}
summary(Merced_EVI_df$layer)
```

```{r, eval = FALSE}
plot_EVI <- Merced_EVI_df %>%
  ggplot() +
  geom_tile(aes(x = x, y = y, fill = layer)) +
  geom_sf(data = merced_road_shp) +
  xlim(-120.55, -120.40) +
  ylim(37.27, 37.38) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "black", hjust = 0.5, size = 15),
        plot.title = element_text(color = "darkgreen", hjust = 0.5, size = 30)) + 
  scale_fill_gradient(low = "gray", high = "green", name = "EVI") +
  labs(title = "EVI",
       subtitle = "30 Day Map Challenge Day 10: Raster",
       caption = "USGS LandSat8 Data",
       x = "", y = "")
```

# GCI

```{r}
GCI <- NIR / GREEN + 1
```

```{r}
GCI_df <- GCI %>%
  projectRaster(crs = "+proj=longlat +datum=WGS84") %>%
  as("SpatialPixelsDataFrame") %>% 
  as.data.frame()
```

```{r}
Merced_GCI_df <- GCI_df %>%
  filter(x > -120.55) %>%
  filter(x < -120.40) %>%
  filter(y > 37.27) %>%
  filter(y < 37.38)
```

```{r}
summary(Merced_GCI_df$layer)
```

```{r}
plot_GCI <- Merced_GCI_df %>%
  ggplot() +
  geom_tile(aes(x = x, y = y, fill = layer)) +
  geom_sf(data = merced_road_shp) +
  xlim(-120.55, -120.40) +
  ylim(37.27, 37.38) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "black", hjust = 0.5, size = 15),
        plot.title = element_text(color = "darkgreen", hjust = 0.5, size = 30)) + 
  scale_fill_gradient(low = "gray", high = "green", name = "GCI") +
  labs(title = "GCI",
       subtitle = "30 Day Map Challenge Day 10: Raster",
       caption = "USGS LandSat8 Data",
       x = "", y = "")
```


# NBR

```{r}
NBR <- (NIR - SWIR) / (NIR + SWIR)
```

```{r}
NBR_df <- NBR %>%
  projectRaster(crs = "+proj=longlat +datum=WGS84") %>%
  as("SpatialPixelsDataFrame") %>% 
  as.data.frame()
```

```{r}
Merced_NBR_df <- NBR_df %>%
  filter(x > -120.55) %>%
  filter(x < -120.40) %>%
  filter(y > 37.27) %>%
  filter(y < 37.38)
```

```{r}
summary(Merced_NBR_df$layer)
```

```{r}
plot_NBR <- Merced_NBR_df %>%
  ggplot() +
  geom_tile(aes(x = x, y = y, fill = layer)) +
  geom_sf(data = merced_road_shp) +
  xlim(-120.55, -120.40) +
  ylim(37.27, 37.38) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "black", hjust = 0.5, size = 15),
        plot.title = element_text(color = "darkgreen", hjust = 0.5, size = 30)) + 
  scale_fill_gradient(low = "gray", high = "green", name = "NBR") +
  labs(title = "NBR",
       subtitle = "30 Day Map Challenge Day 10: Raster",
       caption = "USGS LandSat8 Data",
       x = "", y = "")
```

# NDVI

```{r}
NDVI <- (NIR - RED) / (NIR + RED)
```

```{r}
NDVI_df <- NDVI %>%
  projectRaster(crs = "+proj=longlat +datum=WGS84") %>%
  as("SpatialPixelsDataFrame") %>% 
  as.data.frame()
```

```{r}
Merced_NDVI_df <- NDVI_df %>%
  filter(x > -120.55) %>%
  filter(x < -120.40) %>%
  filter(y > 37.27) %>%
  filter(y < 37.38)
```

```{r}
summary(Merced_NDVI_df$layer)
```

```{r}
plot_ndvi <- Merced_NDVI_df %>%
  ggplot() +
  geom_tile(aes(x = x, y = y, fill = layer)) +
  geom_sf(data = merced_road_shp) +
  xlim(-120.55, -120.40) +
  ylim(37.27, 37.38) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "black", hjust = 0.5, size = 15),
        plot.title = element_text(color = "darkgreen", hjust = 0.5, size = 30)) + 
  scale_fill_gradient(low = "gray", high = "green", name = "NDVI") +
  labs(title = "NDVI",
       subtitle = "30 Day Map Challenge Day 10: Raster",
       caption = "USGS LandSat8 Data",
       x = "", y = "")
```

# SAVI

```{r}
L <- 0.95
SAVI <- ((NIR - RED) / (NIR + RED + L)) * (1 + L)
```

```{r}
SAVI_df <- SAVI %>%
  projectRaster(crs = "+proj=longlat +datum=WGS84") %>%
  as("SpatialPixelsDataFrame") %>% 
  as.data.frame()
```

```{r}
Merced_SAVI_df <- SAVI_df %>%
  filter(x > -120.55) %>%
  filter(x < -120.40) %>%
  filter(y > 37.27) %>%
  filter(y < 37.38)
```

```{r}
summary(Merced_SAVI_df$layer)
```

```{r}
plot_SAVI <- Merced_SAVI_df %>%
  ggplot() +
  geom_tile(aes(x = x, y = y, fill = layer)) +
  geom_sf(data = merced_road_shp) +
  xlim(-120.55, -120.40) +
  ylim(37.27, 37.38) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "black", 
                                     hjust = 0.5, size = 15),
        plot.title = element_text(color = "darkgreen", 
                                  hjust = 0.5, size = 30)) + 
  scale_fill_gradient(low = "gray", high = "green", name = "SAVI") +
  labs(title = "SAVI",
       subtitle = "30 Day Map Challenge Day 10: Raster",
       caption = "USGS LandSat8 Data",
       x = "", y = "")
```

# SIPI

```{r}
SIPI <- (NIR - BLUE) / (NIR - RED)
```

```{r}
SIPI_df <- SIPI %>%
  projectRaster(crs = "+proj=longlat +datum=WGS84") %>%
  as("SpatialPixelsDataFrame") %>% 
  as.data.frame()
```

```{r}
Merced_SIPI_df <- SIPI_df %>%
  filter(x > -120.55) %>%
  filter(x < -120.40) %>%
  filter(y > 37.27) %>%
  filter(y < 37.38)
```

```{r}
summary(Merced_SIPI_df$layer)
```

```{r}
plot_SIPI <- Merced_SIPI_df %>%
  ggplot() +
  geom_tile(aes(x = x, y = y, fill = layer)) +
  geom_sf(data = merced_road_shp) +
  xlim(-120.55, -120.40) +
  ylim(37.27, 37.38) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "black", hjust = 0.5, size = 15),
        plot.title = element_text(color = "darkgreen", hjust = 0.5, size = 30)) + 
  scale_fill_gradient(low = "gray", high = "green", name = "SIPI") +
  labs(title = "SIPI",
       subtitle = "30 Day Map Challenge Day 10: Raster",
       caption = "USGS LandSat8 Data",
       x = "", y = "")
```