---
title: "Day 11"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("rayshader") #for 3D effects
library("rgeos") #for centroids
library("sf") #handle shape files
library("tidyverse")
```

```{r}
# load shape file
USA_hex_shp <- st_read("us_states_hexgrid/us_states_hexgrid.shp")

# load demographics file
counseling_ranks <- readxl::read_xlsx("counseling_ranks.xlsx")
```

```{r}
# merge data
USA_counseling_ranks <- USA_hex_shp %>%
  left_join(counseling_ranks, by = c("iso3166_2" = "id"))
```


```{r}
# Calculate the centroid of each hexagon to add the label
# https://stackoverflow.com/questions/49343958/do-the-values-returned-by-rgeosgcentroid-and-sfst-centroid-differ
centers <- data.frame(
  st_coordinates(st_centroid(USA_hex_shp$geometry)), 
  id=USA_hex_shp$iso3166_2)
```


```{r}
hex_plot <- USA_counseling_ranks %>%
  ggplot() +
  geom_sf(aes(fill = counseling_access)) +
  geom_text(data = centers, aes(x = X, y = Y, label = id)) +
  scale_fill_continuous(low = "white", high = "blue") + 
  labs(title = "Feeling Blue in the USA",
       subtitle = "30 Day Map Challenge Day 11: 3D",
       caption = "Data Source: https://ct.counseling.org",
       x = "", y = "") +
  theme_minimal() +
  # theme(legend.position = "right") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        plot.subtitle = element_text(color = "blue", hjust = 0.43, size = 10),
        plot.title = element_text(color = "blue", hjust = 0.4, size = 15)) +
  guides(fill = guide_legend(title = "Counseling \nAccess \nRanking"))
```

```{r}
t1 <- proc.time()
plot_gg(hex_plot, multicore = TRUE, windowsize = c(1000, 800))
# Sys.sleep(0.2)
# render_snapshot(clear = TRUE)
t2 <- proc.time()
t2 - t1
```

