---
title: "Day 30"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("sf")
library("tidyverse")
library("wesanderson") #color palette
```

```{r}
# https://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-admin-0-countries-2/
countries_shp_raw <- st_read("ne_50m_admin_0_countries/ne_50m_admin_0_countries.shp")

# https://gist.github.com/graydon/11198540
bounding_boxes <- readxl::read_xlsx("bounding_boxes.xlsx")
```

```{r, eval = FALSE}
countries_shp <- countries_shp_raw %>%
  mutate(ID = 1:nrow(countries_shp_raw)) %>%
  group_by(ID) %>%
  # rowwise() %>%
  mutate(bbox = st_as_sfc( st_bbox(geometry) )) %>%
  ungroup()
```


```{r, eval = FALSE}
countries_shp %>%
  # filter(CONTINENT == "North America") %>%
  mutate(map_color = factor(MAPCOLOR13,
                            levels = 1:13)) %>%
  ggplot() +
  # geom_sf(aes(geometry = bbox,
  geom_sf(aes(geometry = geometry,
              color = map_color, fill = map_color), alpha = 0.25) +
  # coord_sf(crs = "+proj=natearth +lat_0=37.3 +lon_0=146 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs") +
  # scale_color_manual(values = wes_palette(7, name = "Royal1",  type = "continuous")) +
  # xlim(-34, 145) +
  theme(legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "gray25", 
                                     hjust = 0.5, size = 15),
        plot.title = element_text(color = "black", 
                                  hjust = 0.5, size = 20)) + 
  labs(title = "The World",
       subtitle = "30 Day Map Challenge, Day 30: Metamapping",
       caption = "Data Source: Natural Earth",
       x = "", y = "")

```

```{r}
df <- bounding_boxes %>%
  left_join(countries_shp_raw, by = c("ISO3" = "ISO_A3"))
df <- df %>%
  mutate(map_color = factor(MAPCOLOR13, levels = 1:13),
         horiz_range = lon_max - lon_min) %>%
  filter(horiz_range < 270)
```

```{r}
df %>%
  ggplot() +
  geom_rect(aes(xmin = lon_min, xmax = lon_max, ymin = lat_min, ymax = lat_max, 
                color = map_color, fill = map_color), alpha = 0.25) +
  theme(legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "gray25", 
                                     hjust = 0.5, size = 15),
        plot.title = element_text(color = "black", 
                                  hjust = 0.5, size = 20)) + 
  labs(title = "Bounding Boxes of the World",
       subtitle = "30 Day Map Challenge, Day 30: Metamapping",
       caption = "Data Source: OpenStreetMap",
       x = "", y = "")
```

```{r}
df %>%
  filter(CONTINENT == "North America") %>%
  ggplot() +
  geom_rect(aes(xmin = lon_min, xmax = lon_max, ymin = lat_min, ymax = lat_max, 
                color = "white", fill = map_color), alpha = 0.25) +
  scale_fill_manual(values = wes_palette(13, name = "Royal1",  type = "continuous")) +
  theme(legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "gray25", 
                                     hjust = 0.5, size = 15),
        plot.title = element_text(color = "black", 
                                  hjust = 0.5, size = 20)) + 
  labs(title = "Bounding Boxes of the World",
       subtitle = "30 Day Map Challenge, Day 30: Metamapping",
       caption = "Data Source: OpenStreetMap",
       x = "", y = "")
```

