---
title: "Day 12"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("sf") #handle shape files
library("tidyverse")
```

```{r, message = FALSE, warning = FALSE}
# load shape file
CA_county_shp <- st_read("CA_Counties/CA_Counties_TIGER2016.shp")

# load Census data
CA_county_data_raw <- read_csv("cc-est2019-agesex-06.csv")
```

```{r}
gender_df <- CA_county_data_raw %>%
  select(CTYNAME, YEAR, POPESTIMATE, POPEST_MALE) %>%
  filter(YEAR == 12) %>%
  mutate(prop_male = 100*POPEST_MALE / POPESTIMATE,
         majority_male = ifelse(prop_male > 50,
                                "more men", "more women"))

CA_county_shp <- CA_county_shp %>%
  left_join(gender_df, by = c("NAMELSAD" = "CTYNAME"))
```


```{r}
cbbPalette <- c("#E69F00", "#CC79A7")

CA_county_shp %>%
  ggplot() +
  geom_sf(aes(fill = majority_male)) +
  theme(legend.position = c(0.75, 0.75),
        legend.title = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "#E69F00", hjust = 0.5, size = 15),
        plot.title = element_text(color = "#CC79A7", hjust = 0.5, size = 20)) + 
  scale_fill_manual(values=cbbPalette) +
  labs(title = "Gender Proportions",
       subtitle = "30 Day Map Challenge, Day 12: Population",
       caption = "Data Source: US Census")
```

