---
title: "30 Day Map Challenge Day 22"
author: "Derek Sollberger"
format: 
  html:
    toc: true
date: "2022-11-22"
---

```{r}
#| message: false
#| warning: false
library("ggrepel")
library("sf")
library("tidyverse")

knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load shape file(s)
us_cities_shp <- st_read("../data/UScities/citiesx010g.shp")
us_states_shp <- st_read("../data/US_States/cb_2018_us_state_5m.shp")
```

```{r}
# find places whose ANSICODE was "missing" but FEATURE2 was not missing
null_shp <- us_cities_shp |>
  filter(ANSICODE < 0) |>
  filter(FEATURE2 != "-999") |>
  filter(STATE != "HI")
```

```{r}
# make rough map
null_shp |>
  ggplot() +
  geom_sf()
```

```{r}
# make map!
description <- "55 cities in the continential US\n
30 Day Map Challenge, Day 22: NULL\n
Data source: geodata.lib.utexas.edu\n
Map assembled by Derek Sollberger"

lat_min <- 22
lat_max <- 50
long_min <- -130
long_max <- -65

p1 <- us_states_shp |>
  ggplot() +
  geom_sf(color = "gray50", fill = "black") +
  geom_point(aes(x = PopPlLong, y = PopPlLat),
             color = "blue", size = 3,
             data = null_shp) +
  geom_label_repel(aes(x = PopPlLong, y = PopPlLat, label = NAME),
             color = "blue", size = 5,
             data = null_shp) +
  labs(title = "US Cities whose ANSICODE was Missing",
       subtitle = "but whose FEATURE2 field was not Missing",
       caption = description,
       x = "", y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.background = element_rect(fill = "black"),
        plot.title = element_text(color = "white", size = 25),
        plot.subtitle = element_text(color = "white", size = 20),
        plot.caption = element_text(color = "white", hjust = 0, size = 15)) +
  xlim(long_min, long_max) +
  ylim(lat_min, lat_max)
```