---
title: "Day 28"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("sf")
library("tidyverse")
library("wesanderson") #color palette
```

```{r}
# https://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-admin-0-countries-2/
countries_shp <- st_read("../ne_50m_admin_0_countries/ne_50m_admin_0_countries.shp")
```

```{r}
for(lon in 0:359){
  coord_string <- paste0("+proj=laea +lat_0=37.3 +lon_0=",
  lon, " +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs")
  
  temp_plot <- countries_shp %>%
    mutate(map_color = factor(MAPCOLOR7,
                              levels = 1:7)) %>%
    ggplot() +
    geom_sf(aes(fill = map_color)) +
    coord_sf(crs = coord_string) +
    scale_fill_manual(values = wes_palette(7, name = "Zissou1", 
                                           type = "continuous")) +
    theme(legend.position = "none",
          legend.title = element_blank(),
          panel.background = element_blank(),
          panel.grid.minor = element_blank(),
          plot.subtitle = element_text(color = "black", 
                                       hjust = 0.5, size = 15),
          plot.title = element_text(color = "red", 
                                    hjust = 0.5, size = 10)) + 
    labs(title = "30 Day Map Challenge",
         subtitle = "Day 28: The Earth is not Flat",
         caption = "Data Source: Natural Earth",
         x = "", y = "")
  
  dev.new(width = 550, height = 314, units = "px", noRStudioGD = T)
  ggsave(temp_plot, file = paste0("plot", lon, ".jpeg"),
         width = dev.size()[1],
         height = dev.size()[2])
  dev.off()
}

```

