---
title: "Day 24"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("sf")
library("tidyverse")
```

```{r}
# load shape file
countries_shp <- st_read("../ne_50m_admin_0_countries/ne_50m_admin_0_countries.shp")

# load data file
LGBT_df <- readr::read_csv("GAI.csv")
```

```{r}
plot_2003 <- countries_shp %>%
  left_join(LGBT_df %>% filter(year == 2003),
            by = c("NAME" = "country")) %>%
  ggplot() +
  geom_sf(aes(fill = gai)) +
  scale_fill_gradient(name = "Global Acceptance Index",
                      low = "#999247", high = "#8C4799",
                      breaks = c(2,4,6,8),
                      limits = c(1.6, 8.9)) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "#999247", hjust = 0.5, size = 15),
        plot.title = element_text(color = "#8C4799", hjust = 0.5, size = 20)) + 
  labs(title = "Global Acceptance Index of LGBT (2003)",
       subtitle = "30 Day Map Challenge, Day 24: Historical Map",
       caption = "Data Source: Williams Institute at UCLA",
       x = "", y = "")

dev.new(width = 1100, height = 628, units = "px", noRStudioGD = T)
ggsave(plot_2003, file = "plot_2003.jpeg",
       width = dev.size()[1],
       height = dev.size()[2])
dev.off()
```
```{r}
plot_2008 <- countries_shp %>%
  left_join(LGBT_df %>% filter(year == 2008),
            by = c("NAME" = "country")) %>%
  ggplot() +
  geom_sf(aes(fill = gai)) +
  scale_fill_gradient(name = "Global Acceptance Index",
                      low = "#999247", high = "#8C4799",
                      breaks = c(2,4,6,8),
                      limits = c(1.6, 8.9)) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "#999247", hjust = 0.5, size = 15),
        plot.title = element_text(color = "#8C4799", hjust = 0.5, size = 20)) + 
  labs(title = "Global Acceptance Index of LGBT (2008)",
       subtitle = "30 Day Map Challenge, Day 24: Historical Map",
       caption = "Data Source: Williams Institute at UCLA",
       x = "", y = "")

dev.new(width = 1100, height = 628, units = "px", noRStudioGD = T)
ggsave(plot_2008, file = "plot_2008.jpeg",
       width = dev.size()[1],
       height = dev.size()[2])
dev.off()
```

```{r}
plot_2013 <- countries_shp %>%
  left_join(LGBT_df %>% filter(year == 2013),
            by = c("NAME" = "country")) %>%
  ggplot() +
  geom_sf(aes(fill = gai)) +
  scale_fill_gradient(name = "Global Acceptance Index",
                      low = "#999247", high = "#8C4799",
                      breaks = c(2,4,6,8),
                      limits = c(1.6, 8.9)) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "#999247", hjust = 0.5, size = 15),
        plot.title = element_text(color = "#8C4799", hjust = 0.5, size = 20)) + 
  labs(title = "Global Acceptance Index of LGBT (2013)",
       subtitle = "30 Day Map Challenge, Day 24: Historical Map",
       caption = "Data Source: Williams Institute at UCLA",
       x = "", y = "")

dev.new(width = 1100, height = 628, units = "px", noRStudioGD = T)
ggsave(plot_2013, file = "plot_2013.jpeg",
       width = dev.size()[1],
       height = dev.size()[2])
dev.off()
```

```{r}
plot_2017 <- countries_shp %>%
  left_join(LGBT_df %>% filter(year == 2017),
            by = c("NAME" = "country")) %>%
  ggplot() +
  geom_sf(aes(fill = gai)) +
  scale_fill_gradient(name = "Global Acceptance Index",
                      low = "#999247", high = "#8C4799",
                      breaks = c(2,4,6,8),
                      limits = c(1.6, 8.9)) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "#999247", hjust = 0.5, size = 15),
        plot.title = element_text(color = "#8C4799", hjust = 0.5, size = 20)) + 
  labs(title = "Global Acceptance Index of LGBT (2017)",
       subtitle = "30 Day Map Challenge, Day 24: Historical Map",
       caption = "Data Source: Williams Institute at UCLA",
       x = "", y = "")

dev.new(width = 1100, height = 628, units = "px", noRStudioGD = T)
ggsave(plot_2017, file = "plot_2017.jpeg",
       width = dev.size()[1],
       height = dev.size()[2])
dev.off()
```

