---
title: "30 Day Map Challenge Day 25"
author: "Derek Sollberger"
format: 
  html:
    toc: true
date: "2022-11-25"
---

```{r}
#| message: false
#| warning: false
library("sf")
library("tidyverse")

knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load shape file(s)
# https://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-admin-0-countries-2/
countries_shp <- st_read("../data/ne_50m_admin_0_countries/ne_50m_admin_0_countries.shp")
```

```{r}
# find total population
sum(countries_shp$POP_EST)

# find half population
half_pop <- sum(countries_shp$POP_EST) / 2

countries_df <- countries_shp |>
  arrange(desc(POP_EST)) |>
  mutate(cum_pop = cumsum(POP_EST)) |>
  mutate(pop_class = ifelse(cum_pop < half_pop,
                            "half of population",
                            "1/2 of population"))
```

```{r}
# lat_min <- 25.5
# lat_max <- 48.5
# long_min <- -124
# long_max <- -69

countries_df |>
  ggplot() +
  geom_sf(aes(fill = pop_class), color = "white") +
  labs(title = "The World's Population In Two Halves",
       subtitle = "30 Day Map Challenge, Day 25: Two Colors",
       caption = "Derek Sollberger") +
  
  # https://www.sessions.edu/color-calculator/
  scale_fill_manual(values = c("#0F8040", "#801c0F")) +
  
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom",
        legend.text = element_text(size = 30),
        legend.title = element_blank(),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.background = element_rect(fill = "white"),
        plot.title = element_text(color = "#0F8040", 
                                  hjust = 0.5,
                                  size = 30),
        plot.subtitle = element_text(color = "#801c0F",
                                     hjust = 0.5,
                                     size = 20),
        plot.caption = element_text(color = "#801c0F", 
                                    hjust = 0.5,
                                    size = 10))
```
