---
title: "Day 21"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ggpubr")
library("jpeg")
library("sf") #handle shape files
library("tidyverse")
```

```{r}
# load shape file
CA_county_shp <- st_read("CA_Counties/CA_Counties_TIGER2016.shp")

# load data file
CA_peaks <- readxl::read_xlsx("CA_peaks.xlsx")
```

```{r}
df <- CA_county_shp %>%
  left_join(CA_peaks, by = c("NAME" = "County"))
```


```{r}
df %>%
  ggplot() +
  # background_image(readJPEG("1200px-Valley_View_Yosemite_August_2013_002.jpg")) +
  geom_sf(aes(fill = Height)) +
  scale_fill_gradient(name = "Elevation of Highest\nPeak (feet)", low = "darkgreen", high = "red") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = c(0.80, 0.75),
        # legend.title = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "blue", hjust = 0.5, size = 15),
        plot.title = element_text(color = "black", hjust = 0.5, size = 20)) + 
  labs(title = "California Peaks",
       subtitle = "30 Day Map Challenge, Day 21: Elevation",
       caption = "Data Sources: PeakBagger and NOAA",
       x = "", y = "")
```

