---
title: "Day 27"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("rasterVis")
library("terra")
library("tidyverse")
```

```{r}
ca_rain_tif <- terra::rast("stanford-qd450mp3166-geotiff.tif")
ca_rain_sample <- terra::aggregate(ca_rain_tif, fact = 10)
ca_rain_df <- as.data.frame(ca_rain_sample, xy = TRUE)
colnames(ca_rain_df) <- c("x", "y", "rain")

round_any = function(x, accuracy, f=round){f(x/ accuracy) * accuracy}

ca_rain_df <- ca_rain_df %>%
  mutate(round_x = round(x, 1),
         round_y = round_any(y, 0.2)) %>%
  group_by(round_x, round_y) %>%
  mutate(avg_rain = mean(rain, na.rm = TRUE)) %>%
  ungroup() %>%
  select(round_x, round_y, avg_rain)


```

```{r}
# ca_rain_df %>%
#   ggplot(aes(x = x, y = y)) +
#   geom_raster(aes(fill = rain))
main_plot <- ca_rain_df %>%
  ggplot() +
  geom_point(aes(x = round_x, y = round_y, 
                 color = log(avg_rain),
                 size = log(avg_rain))) +
  scale_color_gradient(name = "log(average rainfall)\n(inches)",
                       low = "red", high = "blue") +
  scale_size(range = c(0,3)) +
  guides(size = "none") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = c(0.7, 0.8),
        # legend.title = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "red", hjust = 0.5, size = 15),
        plot.title = element_text(color = "blue", hjust = 0.5, size = 20)) + 
  labs(title = "Average Rainfall in California (1981 to 2010)",
       subtitle = "30 Day Map Challenge, Day 27: Heatmap",
       caption = "Data Source: UC Berkeley Library Geodata",
       x = "", y = "")
```

