---
title: "Day 18"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ggpubr")
library("jpeg")
library("sf") #handle shape files
library("tidyverse")
```

```{r}
# load shape file
# https://water.usgs.gov/GIS/metadata/usgswrd/XML/pp1766_cvhm_sfr_network.xml#stdorder
basin_shp <- st_read("pp1766_cvhm_sfr_network/cvhm_sfr_network.shp")
CA_county_shp <- st_read("CA_Counties/CA_Counties_TIGER2016.shp")
```


```{r}
CA_county_shp %>%
  ggplot() +
  background_image(readJPEG("1200px-Valley_View_Yosemite_August_2013_002.jpg")) +
  geom_sf() +
  geom_sf(data = basin_shp, color = "blue") +
          # aes(fill = NAME)) +
  # geom_sf_label(data = basin_shp, 
  #               aes(label = NAME),
  #               label.size = 0.001) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "blue", hjust = 0.5, size = 15),
        plot.title = element_text(color = "black", hjust = 0.5, size = 20)) + 
  labs(title = "California Central Valley",
       subtitle = "30 Day Map Challenge, Day 18: Water",
       caption = "Data Source: USGS Central Valley Hydrologic Model Database\nImage Source: https://en.wikipedia.org/wiki/Merced_River",
       x = "", y = "")
```

