---
title: "Day 20"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("diagram")
library("ggpubr")
library("jpeg")
library("sf") #handle shape files
library("tidyverse")
```

```{r}
# load shape file
# https://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-admin-0-countries-2/
countries_shp <- st_read("../ne_50m_admin_0_countries/ne_50m_admin_0_countries.shp")

# load data file
carmen_sandiego_df <- readxl::read_xlsx("Carmen_Sandiego.xlsx")
```

```{r}
# carmen_sandiego_sf <- st_as_sf(x = carmen_sandiego_df,
#                                coords = c("lat", "long"),
#                         crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")
```


```{r}
title_string <- "Where in the World is Carmen Sandiego?"
subtitle_string <- "30 Day Map Challenge, Day 20: Movement"

for(i in 1:28){
  temp_plot <- countries_shp %>%
    ggplot() +
    # background_image(readJPEG("Carmen_Sandiego_logo.jpg")) +
    geom_sf() +
    geom_segment(data = carmen_sandiego_df,
                 aes(x = long[i], y = lat[i], xend = long[i+1], yend = lat[i+1]),
                 arrow = arrow(), 
                 color = "red", lineend = "butt", linejoin = "round",
                 size = 2) +
    theme(legend.position = "right",
          legend.title = element_blank(),
          panel.background = element_blank(),
          panel.grid.minor = element_blank(),
          plot.subtitle = element_text(color = "black", hjust = 0.5, size = 15),
          plot.title = element_text(color = "red", hjust = 0.5, size = 20)) + 
    labs(title = str_sub(title_string, 1, 10 + i),
         subtitle = str_sub(subtitle_string, 29 - i, 38),
         caption = "Data Source: GeoHack\nLyrics: Rockapella",
         x = "", y = "")
  
  dev.new(width = 1100, height = 628, units = "px", noRStudioGD = T)
  ggsave(temp_plot, file = paste0("plot_", i, ".jpeg"),
         width = dev.size()[1],
         height = dev.size()[2])
  dev.off()
}

```

